/**
 * Embedded migration statements (generated from drizzle/0000_past_iron_fist.sql).
 *
 * Runtime auto-migration executes these directly via db.execute(sql.raw(...)),
 * avoiding the file-reading migrator which breaks inside the Next server bundle.
 * When the schema changes: run \`npm run db:generate\` then \`npm run db:embed\`.
 */

export interface EmbeddedMigration {
  id: string;
  statements: string[];
}

export const embeddedMigrations: EmbeddedMigration[] = [
  {
    id: "0000_init",
    statements: [
          "CREATE TABLE \"activities\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"organization_id\" text,\n\t\"type\" text NOT NULL,\n\t\"entity_type\" text NOT NULL,\n\t\"entity_id\" text NOT NULL,\n\t\"actor_user_id\" text,\n\t\"summary\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
          "CREATE TABLE \"audit_events\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"organization_id\" text,\n\t\"actor_user_id\" text,\n\t\"action\" text NOT NULL,\n\t\"entity_type\" text NOT NULL,\n\t\"entity_id\" text NOT NULL,\n\t\"before_json\" jsonb,\n\t\"after_json\" jsonb,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
          "CREATE TABLE \"buy_requests\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"owner_organization_id\" text,\n\t\"buyer_id\" text NOT NULL,\n\t\"material\" text NOT NULL,\n\t\"min_grade\" text NOT NULL,\n\t\"quantity_kg\" integer NOT NULL,\n\t\"target_price_per_tonne_cents\" bigint NOT NULL,\n\t\"location\" text NOT NULL,\n\t\"country\" text NOT NULL,\n\t\"needed_by\" text,\n\t\"created_at\" text NOT NULL\n);",
          "CREATE TABLE \"companies\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"owner_organization_id\" text,\n\t\"account_organization_id\" text,\n\t\"legal_name\" text NOT NULL,\n\t\"display_name\" text NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"country\" text NOT NULL,\n\t\"business_line\" text NOT NULL,\n\t\"verification\" text NOT NULL,\n\t\"materials\" jsonb NOT NULL,\n\t\"grades\" jsonb NOT NULL,\n\t\"provenance\" text,\n\t\"moq_kg\" integer,\n\t\"capacity_kg\" integer,\n\t\"incoterms\" jsonb,\n\t\"payment_terms\" text,\n\t\"lead_time_days\" integer,\n\t\"supplier_metrics\" jsonb,\n\t\"buyer_metrics\" jsonb,\n\t\"quality_incidents\" integer,\n\t\"last_contact_at\" text,\n\t\"notes\" text\n);",
          "CREATE TABLE \"contacts\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"company_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"role\" text,\n\t\"phone\" text,\n\t\"email\" text,\n\t\"memory\" jsonb NOT NULL\n);",
          "CREATE TABLE \"deals\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"owner_organization_id\" text,\n\t\"title\" text NOT NULL,\n\t\"buyer_id\" text NOT NULL,\n\t\"supplier_id\" text,\n\t\"material\" text NOT NULL,\n\t\"quantity_kg\" integer NOT NULL,\n\t\"stage\" text NOT NULL,\n\t\"sale_price_per_tonne_cents\" bigint NOT NULL,\n\t\"purchase_price_per_tonne_cents\" bigint NOT NULL,\n\t\"close_probability\" double precision NOT NULL,\n\t\"owner_id\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\t\"last_contact_at\" text,\n\t\"next_action\" text,\n\t\"next_action_at\" text,\n\t\"documents\" jsonb NOT NULL,\n\t\"risk_flags\" jsonb NOT NULL,\n\t\"business_line\" text NOT NULL\n);",
          "CREATE TABLE \"decisions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"organization_id\" text,\n\t\"title\" text NOT NULL,\n\t\"context\" text NOT NULL,\n\t\"decision\" text NOT NULL,\n\t\"rationale\" text NOT NULL,\n\t\"expected_outcome\" text NOT NULL,\n\t\"actual_outcome\" text,\n\t\"review_at\" text,\n\t\"status\" text NOT NULL,\n\t\"created_at\" text NOT NULL\n);",
          "CREATE TABLE \"documents\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"organization_id\" text,\n\t\"type\" text NOT NULL,\n\t\"company_id\" text,\n\t\"deal_id\" text,\n\t\"issue_date\" text,\n\t\"expiry_date\" text,\n\t\"verification_status\" text NOT NULL,\n\t\"verified_at\" text,\n\t\"verified_by\" text,\n\t\"storage_key\" text,\n\t\"notes\" text\n);",
          "CREATE TABLE \"follow_ups\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"deal_id\" text,\n\t\"company_id\" text NOT NULL,\n\t\"action\" text NOT NULL,\n\t\"owner_id\" text NOT NULL,\n\t\"priority\" text NOT NULL,\n\t\"due_at\" text NOT NULL,\n\t\"last_contact_at\" text,\n\t\"done\" integer DEFAULT 0 NOT NULL\n);",
          "CREATE TABLE \"materials\" (\n\t\"code\" text PRIMARY KEY NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"is_mvp\" integer DEFAULT 0 NOT NULL\n);",
          "CREATE TABLE \"memberships\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"organization_id\" text NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"status\" text DEFAULT 'ACTIVE' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
          "CREATE TABLE \"organizations\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"legal_name\" text NOT NULL,\n\t\"display_name\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"country\" text NOT NULL,\n\t\"status\" text DEFAULT 'ACTIVE' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"organizations_slug_unique\" UNIQUE(\"slug\")\n);",
          "CREATE TABLE \"quotes\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"organization_id\" text,\n\t\"supplier_id\" text,\n\t\"buyer_id\" text NOT NULL,\n\t\"material\" text NOT NULL,\n\t\"grade\" text NOT NULL,\n\t\"quantity_kg\" integer NOT NULL,\n\t\"purchase_price_per_tonne_cents\" bigint NOT NULL,\n\t\"transport_cents\" bigint NOT NULL,\n\t\"insurance_cents\" bigint NOT NULL,\n\t\"customs_fees_cents\" bigint NOT NULL,\n\t\"financing_cents\" bigint NOT NULL,\n\t\"other_costs_cents\" bigint NOT NULL,\n\t\"desired_margin_percent\" double precision NOT NULL,\n\t\"created_at\" text NOT NULL\n);",
          "CREATE TABLE \"sell_offers\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"owner_organization_id\" text,\n\t\"supplier_id\" text NOT NULL,\n\t\"material\" text NOT NULL,\n\t\"grade\" text NOT NULL,\n\t\"provenance\" text NOT NULL,\n\t\"quantity_kg\" integer NOT NULL,\n\t\"price_per_tonne_cents\" bigint NOT NULL,\n\t\"location\" text NOT NULL,\n\t\"country\" text NOT NULL,\n\t\"available_until\" text,\n\t\"incoterms\" jsonb,\n\t\"documents\" jsonb NOT NULL,\n\t\"created_at\" text NOT NULL\n);",
          "CREATE TABLE \"users\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"avatar_url\" text,\n\t\"password_hash\" text NOT NULL,\n\t\"password_salt\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"users_email_unique\" UNIQUE(\"email\")\n);",
          "ALTER TABLE \"activities\" ADD CONSTRAINT \"activities_organization_id_organizations_id_fk\" FOREIGN KEY (\"organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"activities\" ADD CONSTRAINT \"activities_actor_user_id_users_id_fk\" FOREIGN KEY (\"actor_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"audit_events\" ADD CONSTRAINT \"audit_events_organization_id_organizations_id_fk\" FOREIGN KEY (\"organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"audit_events\" ADD CONSTRAINT \"audit_events_actor_user_id_users_id_fk\" FOREIGN KEY (\"actor_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"buy_requests\" ADD CONSTRAINT \"buy_requests_owner_organization_id_organizations_id_fk\" FOREIGN KEY (\"owner_organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"buy_requests\" ADD CONSTRAINT \"buy_requests_buyer_id_companies_id_fk\" FOREIGN KEY (\"buyer_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"companies\" ADD CONSTRAINT \"companies_owner_organization_id_organizations_id_fk\" FOREIGN KEY (\"owner_organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"companies\" ADD CONSTRAINT \"companies_account_organization_id_organizations_id_fk\" FOREIGN KEY (\"account_organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"contacts\" ADD CONSTRAINT \"contacts_company_id_companies_id_fk\" FOREIGN KEY (\"company_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_owner_organization_id_organizations_id_fk\" FOREIGN KEY (\"owner_organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_buyer_id_companies_id_fk\" FOREIGN KEY (\"buyer_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"deals\" ADD CONSTRAINT \"deals_supplier_id_companies_id_fk\" FOREIGN KEY (\"supplier_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"decisions\" ADD CONSTRAINT \"decisions_organization_id_organizations_id_fk\" FOREIGN KEY (\"organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"documents\" ADD CONSTRAINT \"documents_organization_id_organizations_id_fk\" FOREIGN KEY (\"organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"documents\" ADD CONSTRAINT \"documents_company_id_companies_id_fk\" FOREIGN KEY (\"company_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"documents\" ADD CONSTRAINT \"documents_deal_id_deals_id_fk\" FOREIGN KEY (\"deal_id\") REFERENCES \"public\".\"deals\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"follow_ups\" ADD CONSTRAINT \"follow_ups_deal_id_deals_id_fk\" FOREIGN KEY (\"deal_id\") REFERENCES \"public\".\"deals\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"follow_ups\" ADD CONSTRAINT \"follow_ups_company_id_companies_id_fk\" FOREIGN KEY (\"company_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"memberships\" ADD CONSTRAINT \"memberships_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"memberships\" ADD CONSTRAINT \"memberships_organization_id_organizations_id_fk\" FOREIGN KEY (\"organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"quotes\" ADD CONSTRAINT \"quotes_organization_id_organizations_id_fk\" FOREIGN KEY (\"organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"quotes\" ADD CONSTRAINT \"quotes_supplier_id_companies_id_fk\" FOREIGN KEY (\"supplier_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"quotes\" ADD CONSTRAINT \"quotes_buyer_id_companies_id_fk\" FOREIGN KEY (\"buyer_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"sell_offers\" ADD CONSTRAINT \"sell_offers_owner_organization_id_organizations_id_fk\" FOREIGN KEY (\"owner_organization_id\") REFERENCES \"public\".\"organizations\"(\"id\") ON DELETE no action ON UPDATE no action;",
          "ALTER TABLE \"sell_offers\" ADD CONSTRAINT \"sell_offers_supplier_id_companies_id_fk\" FOREIGN KEY (\"supplier_id\") REFERENCES \"public\".\"companies\"(\"id\") ON DELETE no action ON UPDATE no action;"
    ],
  },
];
