/**
 * Seed dataset for EN CUIVRE OS.
 *
 * Realistic but CLEARLY FICTIONAL. This is the V1 data source (no external DB).
 * All prices are cents per tonne (see lib/money.ts), quantities in kg.
 *
 * Counts (asserted in tests/seed.test.ts):
 *   5 suppliers, 7 buyers, 3 BOTH, 12 sell offers, 15 buy requests, 8 deals,
 *   documents with mixed statuses, follow-ups, quotes.
 */

import { eur } from "../money";
import type {
  BuyRequest,
  Company,
  Contact,
  Deal,
  Decision,
  FollowUp,
  Quote,
  SellOffer,
  TrackedDocument,
} from "../types";
import { daysAgo, daysFromNow } from "./dates";

export const companies: Company[] = [
  // ---------- SUPPLIERS (5) ----------
  {
    id: "sup-metalsud",
    legalName: "MétalSud Distribution SAS",
    displayName: "MétalSud",
    role: "SUPPLIER",
    country: "France",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["COPPER_BARS_BUSBARS", "COPPER_SHEETS_PLATES", "BRASS"],
    grades: ["A", "B"],
    provenance: "DISTRIBUTOR",
    moqKg: 500,
    capacityKg: 40000,
    incoterms: { code: "FCA", place: "Marseille" },
    paymentTerms: "30 j fin de mois",
    leadTimeDays: 5,
    supplierMetrics: {
      pricing: 74,
      quality: 82,
      reliability: 80,
      availability: 70,
      compliance: 78,
      speed: 76,
      communication: 72,
      terms: 70,
    },
    qualityIncidents: 0,
    lastContactAt: daysAgo(2),
    notes: "Partenaire régulier sur les busbars.",
  },
  {
    id: "sup-recyclyon",
    legalName: "Recycl'Lyon EURL",
    displayName: "Recycl'Lyon",
    role: "SUPPLIER",
    country: "France",
    businessLine: "CIRCULAR",
    verification: "VERIFIED",
    materials: ["COPPER_MILLBERRY", "BRASS", "ALUMINIUM"],
    grades: ["A", "B", "C"],
    provenance: "LOCAL_SCRAP",
    moqKg: 200,
    capacityKg: 12000,
    incoterms: { code: "EXW", place: "Lyon" },
    paymentTerms: "Comptant",
    leadTimeDays: 2,
    supplierMetrics: {
      pricing: 82,
      quality: 68,
      reliability: 72,
      availability: 66,
      compliance: 60,
      speed: 84,
      communication: 70,
      terms: 65,
    },
    qualityIncidents: 1,
    lastContactAt: daysAgo(9),
    notes: "Chutes d'électriciens, volumes irréguliers mais bon prix.",
  },
  {
    id: "sup-katanga",
    legalName: "Katanga Metals SARL",
    displayName: "Katanga Metals",
    role: "SUPPLIER",
    country: "RD Congo",
    businessLine: "CONGO",
    verification: "PENDING",
    materials: ["COPPER_CATHODE_GRADE_A"],
    grades: ["A"],
    provenance: "DIRECT_PRODUCER",
    moqKg: 5000,
    capacityKg: 80000,
    incoterms: { code: "FOB", place: "Durban" },
    paymentTerms: "LC à vue",
    leadTimeDays: 35,
    supplierMetrics: {
      pricing: 88,
      quality: 76,
      reliability: 55,
      availability: 78,
      compliance: 45,
      speed: 40,
      communication: 58,
      terms: 50,
    },
    qualityIncidents: 0,
    lastContactAt: daysAgo(20),
    notes: "Corridor RDC->Europe. Vérification en cours, documents incomplets.",
  },
  {
    id: "sup-brassco",
    legalName: "BrassCo Trading SAS",
    displayName: "BrassCo",
    role: "SUPPLIER",
    country: "France",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["BRASS", "BRONZE", "COPPER_TUBES"],
    grades: ["A", "B"],
    provenance: "TRADER",
    moqKg: 300,
    capacityKg: 25000,
    incoterms: { code: "CIF", place: "Anvers" },
    paymentTerms: "30 j",
    leadTimeDays: 8,
    supplierMetrics: {
      pricing: 70,
      quality: 90,
      reliability: 88,
      availability: 80,
      compliance: 86,
      speed: 78,
      communication: 84,
      terms: 80,
    },
    qualityIncidents: 0,
    lastContactAt: daysAgo(1),
    notes: "Fournisseur stratégique laiton/bronze.",
  },
  {
    id: "sup-globalscrap",
    legalName: "GlobalScrap Ltd",
    displayName: "GlobalScrap",
    role: "SUPPLIER",
    country: "Inconnu",
    businessLine: "TRADE",
    verification: "REJECTED",
    materials: ["COPPER_CATHODE_GRADE_A", "COPPER_MILLBERRY"],
    grades: ["A"],
    provenance: "TRADER",
    moqKg: 20000,
    capacityKg: 200000,
    incoterms: { code: "FOB" },
    paymentTerms: "Acompte 50% avant expédition",
    leadTimeDays: 15,
    supplierMetrics: {
      pricing: 98,
      quality: 40,
      reliability: 20,
      availability: 90,
      compliance: 10,
      speed: 30,
      communication: 25,
      terms: 15,
    },
    qualityIncidents: 3,
    lastContactAt: daysAgo(30),
    notes: "[BLOCKED] Prix trop beau, acompte suspect, société non identifiable.",
  },

  // ---------- BUYERS (7) ----------
  {
    id: "buy-cableplus",
    legalName: "CâblePlus Industries SA",
    displayName: "CâblePlus",
    role: "BUYER",
    country: "France",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["COPPER_CATHODE_GRADE_A", "COPPER_BARS_BUSBARS"],
    grades: ["A"],
    buyerMetrics: {
      buyingVolumeKg: 60000,
      frequency: 14,
      paymentReliability: 92,
      closingSpeed: 85,
      grossMarginGeneratedCents: eur(72000),
      relationship: 88,
      repeatPurchases: 18,
    },
    lastContactAt: daysAgo(3),
    notes: "[VIP] Gros consommateur de cathode.",
  },
  {
    id: "buy-fonderie",
    legalName: "Fonderie Rhône SAS",
    displayName: "Fonderie Rhône",
    role: "BUYER",
    country: "France",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["COPPER_MILLBERRY", "BRASS", "BRONZE"],
    grades: ["A", "B"],
    buyerMetrics: {
      buyingVolumeKg: 22000,
      frequency: 8,
      paymentReliability: 80,
      closingSpeed: 70,
      grossMarginGeneratedCents: eur(28000),
      relationship: 74,
      repeatPurchases: 9,
    },
    lastContactAt: daysAgo(6),
  },
  {
    id: "buy-elektro",
    legalName: "Elektro Metall GmbH",
    displayName: "Elektro GmbH",
    role: "BUYER",
    country: "Allemagne",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["COPPER_CATHODE_GRADE_A", "COPPER_BARS_BUSBARS"],
    grades: ["A"],
    buyerMetrics: {
      buyingVolumeKg: 45000,
      frequency: 10,
      paymentReliability: 88,
      closingSpeed: 78,
      grossMarginGeneratedCents: eur(51000),
      relationship: 80,
      repeatPurchases: 12,
    },
    lastContactAt: daysAgo(4),
  },
  {
    id: "buy-tubatec",
    legalName: "Tubatec SARL",
    displayName: "Tubatec",
    role: "BUYER",
    country: "France",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["COPPER_TUBES", "COPPER_SHEETS_PLATES"],
    grades: ["A", "B"],
    buyerMetrics: {
      buyingVolumeKg: 8000,
      frequency: 4,
      paymentReliability: 76,
      closingSpeed: 60,
      grossMarginGeneratedCents: eur(9000),
      relationship: 60,
      repeatPurchases: 3,
    },
    lastContactAt: daysAgo(12),
  },
  {
    id: "buy-alumex",
    legalName: "Alumex Profilés SAS",
    displayName: "Alumex",
    role: "BUYER",
    country: "France",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["ALUMINIUM"],
    grades: ["A", "B"],
    buyerMetrics: {
      buyingVolumeKg: 30000,
      frequency: 9,
      paymentReliability: 84,
      closingSpeed: 72,
      grossMarginGeneratedCents: eur(21000),
      relationship: 70,
      repeatPurchases: 7,
    },
    lastContactAt: daysAgo(8),
  },
  {
    id: "buy-comptoir",
    legalName: "Comptoir des Métaux SARL",
    displayName: "Comptoir des Métaux",
    role: "BUYER",
    country: "France",
    businessLine: "TRADE",
    verification: "VERIFIED",
    materials: ["BRASS", "BRONZE", "COPPER_MILLBERRY"],
    grades: ["A", "B", "C"],
    buyerMetrics: {
      buyingVolumeKg: 15000,
      frequency: 2,
      paymentReliability: 78,
      closingSpeed: 55,
      grossMarginGeneratedCents: eur(12000),
      relationship: 50,
      repeatPurchases: 5,
    },
    lastContactAt: daysAgo(120),
    notes: "Ancien bon client, silencieux depuis 4 mois.",
  },
  {
    id: "buy-quickcash",
    legalName: "QuickCash Trading",
    displayName: "QuickCash",
    role: "BUYER",
    country: "Inconnu",
    businessLine: "TRADE",
    verification: "UNVERIFIED",
    materials: ["COPPER_CATHODE_GRADE_A", "COPPER_MILLBERRY"],
    grades: ["A", "B"],
    buyerMetrics: {
      buyingVolumeKg: 40000,
      frequency: 6,
      paymentReliability: 25,
      closingSpeed: 90,
      grossMarginGeneratedCents: eur(4000),
      relationship: 20,
      repeatPurchases: 1,
    },
    lastContactAt: daysAgo(5),
    notes: "Pousse à conclure vite, paiement peu fiable.",
  },

  // ---------- BOTH (3) ----------
  {
    id: "both-recupro",
    legalName: "RécuPro Métaux SAS",
    displayName: "RécuPro",
    role: "BOTH",
    country: "France",
    businessLine: "CIRCULAR",
    verification: "VERIFIED",
    materials: ["COPPER_MILLBERRY", "COPPER_SHEETS_PLATES", "BRASS", "ALUMINIUM"],
    grades: ["A", "B", "C"],
    provenance: "INDUSTRIAL_OFFCUT",
    moqKg: 250,
    capacityKg: 18000,
    incoterms: { code: "EXW", place: "Saint-Étienne" },
    paymentTerms: "Comptant achat / 30 j vente",
    leadTimeDays: 3,
    supplierMetrics: {
      pricing: 80,
      quality: 72,
      reliability: 78,
      availability: 74,
      compliance: 70,
      speed: 80,
      communication: 76,
      terms: 72,
    },
    buyerMetrics: {
      buyingVolumeKg: 10000,
      frequency: 5,
      paymentReliability: 82,
      closingSpeed: 68,
      grossMarginGeneratedCents: eur(9000),
      relationship: 72,
      repeatPurchases: 6,
    },
    qualityIncidents: 0,
    lastContactAt: daysAgo(7),
    notes: "Chutes industrielles hors-format, idéal faible capital.",
  },
  {
    id: "both-metalcorridor",
    legalName: "Metal Corridor SARL",
    displayName: "Metal Corridor",
    role: "BOTH",
    country: "RD Congo / France",
    businessLine: "CONGO",
    verification: "PENDING",
    materials: ["COPPER_CATHODE_GRADE_A", "COPPER_MILLBERRY"],
    grades: ["A"],
    provenance: "TRADER",
    moqKg: 3000,
    capacityKg: 60000,
    incoterms: { code: "CIF", place: "Anvers" },
    paymentTerms: "50% acompte / 50% doc",
    leadTimeDays: 28,
    supplierMetrics: {
      pricing: 84,
      quality: 70,
      reliability: 60,
      availability: 76,
      compliance: 52,
      speed: 48,
      communication: 66,
      terms: 58,
    },
    buyerMetrics: {
      buyingVolumeKg: 20000,
      frequency: 4,
      paymentReliability: 70,
      closingSpeed: 62,
      grossMarginGeneratedCents: eur(15000),
      relationship: 64,
      repeatPurchases: 3,
    },
    qualityIncidents: 0,
    lastContactAt: daysAgo(15),
    notes: "Corridor RDC. Vérification en cours.",
  },
  {
    id: "both-atelierlaiton",
    legalName: "Atelier Laiton & Co",
    displayName: "Atelier Laiton",
    role: "BOTH",
    country: "France",
    businessLine: "ATELIER",
    verification: "VERIFIED",
    materials: ["BRASS", "BRONZE"],
    grades: ["A"],
    provenance: "INDUSTRIAL_OFFCUT",
    moqKg: 50,
    capacityKg: 3000,
    incoterms: { code: "EXW", place: "Paris" },
    paymentTerms: "Comptant",
    leadTimeDays: 4,
    supplierMetrics: {
      pricing: 65,
      quality: 92,
      reliability: 85,
      availability: 60,
      compliance: 80,
      speed: 70,
      communication: 88,
      terms: 75,
    },
    buyerMetrics: {
      buyingVolumeKg: 2000,
      frequency: 6,
      paymentReliability: 90,
      closingSpeed: 80,
      grossMarginGeneratedCents: eur(6000),
      relationship: 86,
      repeatPurchases: 8,
    },
    qualityIncidents: 0,
    lastContactAt: daysAgo(5),
    notes: "Premium : gravure, martelage, séries limitées.",
  },
];

export const contacts: Contact[] = [
  {
    id: "ct-metalsud",
    companyId: "sup-metalsud",
    name: "Julien Marchand",
    role: "Directeur commercial",
    phone: "+33 6 12 34 56 78",
    email: "j.marchand@metalsud.example",
    memory: {
      dealsIn: "Busbars et plaques cuivre, laiton",
      usualVolume: "5–15 t / mois",
      lastDiscussion: "A confirmé 12 t de busbars grade A disponibles",
      lastObjection: "Veut un engagement d'enlèvement sous 10 j",
      commitment: "Nous tient un lot de 12 t jusqu'à vendredi",
      nextAction: "Confirmer l'enlèvement avant vendredi",
    },
  },
  {
    id: "ct-cableplus",
    companyId: "buy-cableplus",
    name: "Sophie Bernard",
    role: "Acheteuse matières",
    phone: "+33 6 98 76 54 32",
    email: "s.bernard@cableplus.example",
    memory: {
      dealsIn: "Cathode cuivre grade A",
      usualVolume: "20–30 t / mois",
      lastDiscussion: "Cherche 25 t de cathode pour septembre",
      lastObjection: "Sensible au premium LME",
      commitment: "Attend notre offre ferme",
      nextAction: "Envoyer offre 25 t cathode",
    },
  },
  {
    id: "ct-comptoir",
    companyId: "buy-comptoir",
    name: "Marc Dubois",
    role: "Gérant",
    phone: "+33 6 45 67 89 01",
    email: "m.dubois@comptoir-metaux.example",
    memory: {
      dealsIn: "Laiton, bronze, millberry",
      usualVolume: "5–10 t / trimestre",
      lastDiscussion: "Dernier achat il y a 4 mois",
      lastObjection: "Prix jugé un peu haut sur le bronze",
      commitment: "—",
      nextAction: "Relancer pour réactiver le compte",
    },
  },
];

export const sellOffers: SellOffer[] = [
  {
    id: "so-1",
    supplierId: "sup-metalsud",
    material: "COPPER_BARS_BUSBARS",
    grade: "A",
    provenance: "DISTRIBUTOR",
    quantityKg: 12000,
    pricePerTonneCents: eur(9350),
    location: "Marseille",
    country: "France",
    availableUntil: daysFromNow(6),
    incoterms: { code: "FCA", place: "Marseille" },
    documents: ["COA", "ORIGIN", "INVOICE"],
    createdAt: daysAgo(3),
  },
  {
    id: "so-2",
    supplierId: "sup-metalsud",
    material: "COPPER_SHEETS_PLATES",
    grade: "B",
    provenance: "DISTRIBUTOR",
    quantityKg: 4000,
    pricePerTonneCents: eur(9800),
    location: "Marseille",
    country: "France",
    documents: ["COA", "INVOICE"],
    createdAt: daysAgo(5),
  },
  {
    id: "so-3",
    supplierId: "sup-recyclyon",
    material: "COPPER_MILLBERRY",
    grade: "A",
    provenance: "LOCAL_SCRAP",
    quantityKg: 3500,
    pricePerTonneCents: eur(7650),
    location: "Lyon",
    country: "France",
    availableUntil: daysFromNow(10),
    incoterms: { code: "EXW", place: "Lyon" },
    documents: ["INVOICE"],
    createdAt: daysAgo(2),
  },
  {
    id: "so-4",
    supplierId: "sup-recyclyon",
    material: "BRASS",
    grade: "B",
    provenance: "LOCAL_SCRAP",
    quantityKg: 2200,
    pricePerTonneCents: eur(5150),
    location: "Lyon",
    country: "France",
    documents: [],
    createdAt: daysAgo(8),
  },
  {
    id: "so-5",
    supplierId: "sup-recyclyon",
    material: "ALUMINIUM",
    grade: "B",
    provenance: "LOCAL_SCRAP",
    quantityKg: 6000,
    pricePerTonneCents: eur(2250),
    location: "Lyon",
    country: "France",
    documents: ["INVOICE"],
    createdAt: daysAgo(4),
  },
  {
    id: "so-6",
    supplierId: "sup-katanga",
    material: "COPPER_CATHODE_GRADE_A",
    grade: "A",
    provenance: "DIRECT_PRODUCER",
    quantityKg: 25000,
    pricePerTonneCents: eur(8200),
    location: "Lubumbashi",
    country: "RD Congo",
    availableUntil: daysFromNow(40),
    incoterms: { code: "FOB", place: "Durban" },
    documents: ["ASSAY"],
    createdAt: daysAgo(18),
  },
  {
    id: "so-7",
    supplierId: "sup-brassco",
    material: "BRASS",
    grade: "A",
    provenance: "TRADER",
    quantityKg: 5000,
    pricePerTonneCents: eur(5300),
    location: "Anvers",
    country: "Belgique",
    documents: ["COA", "ORIGIN", "INVOICE"],
    createdAt: daysAgo(6),
  },
  {
    id: "so-8",
    supplierId: "sup-brassco",
    material: "BRONZE",
    grade: "A",
    provenance: "TRADER",
    quantityKg: 3000,
    pricePerTonneCents: eur(6250),
    location: "Anvers",
    country: "Belgique",
    documents: ["COA", "ORIGIN"],
    createdAt: daysAgo(6),
  },
  {
    id: "so-9",
    supplierId: "sup-brassco",
    material: "COPPER_TUBES",
    grade: "A",
    provenance: "TRADER",
    quantityKg: 3500,
    pricePerTonneCents: eur(10700),
    location: "Anvers",
    country: "Belgique",
    documents: ["COA", "INVOICE"],
    createdAt: daysAgo(7),
  },
  {
    id: "so-10",
    supplierId: "both-recupro",
    material: "COPPER_SHEETS_PLATES",
    grade: "B",
    provenance: "INDUSTRIAL_OFFCUT",
    quantityKg: 1800,
    pricePerTonneCents: eur(9200),
    location: "Saint-Étienne",
    country: "France",
    documents: ["INVOICE"],
    createdAt: daysAgo(3),
  },
  {
    id: "so-11",
    supplierId: "both-recupro",
    material: "COPPER_MILLBERRY",
    grade: "A",
    provenance: "INDUSTRIAL_OFFCUT",
    quantityKg: 2600,
    pricePerTonneCents: eur(7500),
    location: "Saint-Étienne",
    country: "France",
    availableUntil: daysFromNow(12),
    documents: ["INVOICE", "COA"],
    createdAt: daysAgo(1),
  },
  {
    id: "so-12",
    supplierId: "both-atelierlaiton",
    material: "BRONZE",
    grade: "A",
    provenance: "INDUSTRIAL_OFFCUT",
    quantityKg: 600,
    pricePerTonneCents: eur(6100),
    location: "Paris",
    country: "France",
    documents: ["INVOICE"],
    createdAt: daysAgo(2),
  },
];

export const buyRequests: BuyRequest[] = [
  {
    id: "br-1",
    buyerId: "buy-cableplus",
    material: "COPPER_CATHODE_GRADE_A",
    minGrade: "A",
    quantityKg: 25000,
    targetPricePerTonneCents: eur(8850),
    location: "Paris",
    country: "France",
    neededBy: daysFromNow(30),
    createdAt: daysAgo(3),
  },
  {
    id: "br-2",
    buyerId: "buy-cableplus",
    material: "COPPER_BARS_BUSBARS",
    minGrade: "A",
    quantityKg: 10000,
    targetPricePerTonneCents: eur(10200),
    location: "Marseille",
    country: "France",
    neededBy: daysFromNow(9),
    createdAt: daysAgo(2),
  },
  {
    id: "br-3",
    buyerId: "buy-fonderie",
    material: "COPPER_MILLBERRY",
    minGrade: "B",
    quantityKg: 3000,
    targetPricePerTonneCents: eur(8100),
    location: "Lyon",
    country: "France",
    neededBy: daysFromNow(14),
    createdAt: daysAgo(4),
  },
  {
    id: "br-4",
    buyerId: "buy-fonderie",
    material: "BRASS",
    minGrade: "B",
    quantityKg: 2000,
    targetPricePerTonneCents: eur(5600),
    location: "Lyon",
    country: "France",
    createdAt: daysAgo(6),
  },
  {
    id: "br-5",
    buyerId: "buy-fonderie",
    material: "BRONZE",
    minGrade: "A",
    quantityKg: 1500,
    targetPricePerTonneCents: eur(6900),
    location: "Lyon",
    country: "France",
    neededBy: daysFromNow(20),
    createdAt: daysAgo(5),
  },
  {
    id: "br-6",
    buyerId: "buy-elektro",
    material: "COPPER_CATHODE_GRADE_A",
    minGrade: "A",
    quantityKg: 20000,
    targetPricePerTonneCents: eur(8780),
    location: "Cologne",
    country: "Allemagne",
    neededBy: daysFromNow(25),
    createdAt: daysAgo(4),
  },
  {
    id: "br-7",
    buyerId: "buy-elektro",
    material: "COPPER_BARS_BUSBARS",
    minGrade: "A",
    quantityKg: 8000,
    targetPricePerTonneCents: eur(10100),
    location: "Cologne",
    country: "Allemagne",
    createdAt: daysAgo(10),
  },
  {
    id: "br-8",
    buyerId: "buy-tubatec",
    material: "COPPER_TUBES",
    minGrade: "A",
    quantityKg: 3000,
    targetPricePerTonneCents: eur(11600),
    location: "Nantes",
    country: "France",
    neededBy: daysFromNow(18),
    createdAt: daysAgo(12),
  },
  {
    id: "br-9",
    buyerId: "buy-tubatec",
    material: "COPPER_SHEETS_PLATES",
    minGrade: "B",
    quantityKg: 1500,
    targetPricePerTonneCents: eur(10500),
    location: "Nantes",
    country: "France",
    createdAt: daysAgo(9),
  },
  {
    id: "br-10",
    buyerId: "buy-alumex",
    material: "ALUMINIUM",
    minGrade: "B",
    quantityKg: 6000,
    targetPricePerTonneCents: eur(2600),
    location: "Lyon",
    country: "France",
    neededBy: daysFromNow(15),
    createdAt: daysAgo(8),
  },
  {
    id: "br-11",
    buyerId: "buy-comptoir",
    material: "BRASS",
    minGrade: "B",
    quantityKg: 2000,
    targetPricePerTonneCents: eur(5550),
    location: "Clermont-Ferrand",
    country: "France",
    createdAt: daysAgo(120),
  },
  {
    id: "br-12",
    buyerId: "buy-quickcash",
    material: "COPPER_CATHODE_GRADE_A",
    minGrade: "A",
    quantityKg: 30000,
    targetPricePerTonneCents: eur(9200),
    location: "Rotterdam",
    country: "Pays-Bas",
    neededBy: daysFromNow(5),
    createdAt: daysAgo(5),
  },
  {
    id: "br-13",
    buyerId: "both-metalcorridor",
    material: "COPPER_MILLBERRY",
    minGrade: "A",
    quantityKg: 4000,
    targetPricePerTonneCents: eur(8000),
    location: "Anvers",
    country: "Belgique",
    createdAt: daysAgo(15),
  },
  {
    id: "br-14",
    buyerId: "both-atelierlaiton",
    material: "BRONZE",
    minGrade: "A",
    quantityKg: 500,
    targetPricePerTonneCents: eur(6800),
    location: "Paris",
    country: "France",
    neededBy: daysFromNow(11),
    createdAt: daysAgo(5),
  },
  {
    id: "br-15",
    buyerId: "both-recupro",
    material: "COPPER_SHEETS_PLATES",
    minGrade: "B",
    quantityKg: 1800,
    targetPricePerTonneCents: eur(9900),
    location: "Saint-Étienne",
    country: "France",
    createdAt: daysAgo(7),
  },
];

export const deals: Deal[] = [
  {
    id: "deal-1",
    title: "Cathode 25 t — CâblePlus",
    buyerId: "buy-cableplus",
    supplierId: "sup-katanga",
    material: "COPPER_CATHODE_GRADE_A",
    quantityKg: 25000,
    stage: "NEGOTIATION",
    salePricePerTonneCents: eur(8850),
    purchasePricePerTonneCents: eur(8200),
    closeProbability: 0.6,
    ownerId: "ceo",
    createdAt: daysAgo(12),
    lastContactAt: daysAgo(2),
    nextAction: "Valider assay et LC avec Katanga",
    nextActionAt: daysFromNow(1),
    documents: ["ASSAY", "INVOICE"],
    riskFlags: ["UNVERIFIED_COMPANY", "MISSING_ORIGIN"],
    businessLine: "TRADE",
  },
  {
    id: "deal-2",
    title: "Busbars 10 t — CâblePlus",
    buyerId: "buy-cableplus",
    supplierId: "sup-metalsud",
    material: "COPPER_BARS_BUSBARS",
    quantityKg: 10000,
    stage: "QUOTED",
    salePricePerTonneCents: eur(10200),
    purchasePricePerTonneCents: eur(9350),
    closeProbability: 0.75,
    ownerId: "ceo",
    createdAt: daysAgo(5),
    lastContactAt: daysAgo(4),
    nextAction: "Relancer sur l'offre envoyée",
    nextActionAt: daysAgo(1),
    documents: ["COA", "ORIGIN", "INVOICE"],
    riskFlags: [],
    businessLine: "TRADE",
  },
  {
    id: "deal-3",
    title: "Cathode 20 t — Elektro",
    buyerId: "buy-elektro",
    supplierId: "sup-katanga",
    material: "COPPER_CATHODE_GRADE_A",
    quantityKg: 20000,
    stage: "QUALIFIED",
    salePricePerTonneCents: eur(8780),
    purchasePricePerTonneCents: eur(8200),
    closeProbability: 0.5,
    ownerId: "ceo",
    createdAt: daysAgo(8),
    lastContactAt: daysAgo(4),
    nextAction: "Chiffrer la logistique FOB Durban -> Anvers",
    nextActionAt: daysFromNow(2),
    documents: ["ASSAY"],
    riskFlags: ["UNVERIFIED_COMPANY", "MISSING_COA"],
    businessLine: "TRADE",
  },
  {
    id: "deal-4",
    title: "Millberry 3 t — Fonderie Rhône",
    buyerId: "buy-fonderie",
    supplierId: "sup-recyclyon",
    material: "COPPER_MILLBERRY",
    quantityKg: 3000,
    stage: "QUOTED",
    salePricePerTonneCents: eur(8100),
    purchasePricePerTonneCents: eur(7650),
    closeProbability: 0.7,
    ownerId: "ceo",
    createdAt: daysAgo(4),
    lastContactAt: daysAgo(3),
    nextAction: "Confirmer enlèvement Lyon",
    nextActionAt: daysFromNow(0),
    documents: ["INVOICE"],
    riskFlags: ["MISSING_COA"],
    businessLine: "TRADE",
  },
  {
    id: "deal-5",
    title: "Laiton 2 t — Fonderie Rhône",
    buyerId: "buy-fonderie",
    supplierId: "sup-brassco",
    material: "BRASS",
    quantityKg: 2000,
    stage: "CONTRACT",
    salePricePerTonneCents: eur(5600),
    purchasePricePerTonneCents: eur(5300),
    closeProbability: 0.9,
    ownerId: "ceo",
    createdAt: daysAgo(10),
    lastContactAt: daysAgo(9),
    nextAction: "Faire signer le contrat",
    nextActionAt: daysAgo(2),
    documents: ["COA", "ORIGIN", "INVOICE"],
    riskFlags: [],
    businessLine: "TRADE",
  },
  {
    id: "deal-6",
    title: "Tubes 3 t — Tubatec",
    buyerId: "buy-tubatec",
    supplierId: "sup-brassco",
    material: "COPPER_TUBES",
    quantityKg: 3000,
    stage: "LEAD",
    salePricePerTonneCents: eur(11600),
    purchasePricePerTonneCents: eur(10700),
    closeProbability: 0.4,
    ownerId: "ceo",
    createdAt: daysAgo(12),
    lastContactAt: daysAgo(12),
    nextAction: "Qualifier le besoin réel",
    nextActionAt: daysFromNow(3),
    documents: [],
    riskFlags: [],
    businessLine: "TRADE",
  },
  {
    id: "deal-7",
    title: "Aluminium 6 t — Alumex",
    buyerId: "buy-alumex",
    supplierId: "sup-recyclyon",
    material: "ALUMINIUM",
    quantityKg: 6000,
    stage: "QUALIFIED",
    salePricePerTonneCents: eur(2600),
    purchasePricePerTonneCents: eur(2250),
    closeProbability: 0.55,
    ownerId: "ceo",
    createdAt: daysAgo(8),
    lastContactAt: daysAgo(6),
    nextAction: "Proposer prix ferme",
    nextActionAt: daysFromNow(2),
    documents: ["INVOICE"],
    riskFlags: [],
    businessLine: "TRADE",
  },
  {
    id: "deal-8",
    title: "Bronze 0,5 t — Atelier signature",
    buyerId: "both-atelierlaiton",
    supplierId: "sup-brassco",
    material: "BRONZE",
    quantityKg: 500,
    stage: "WON",
    salePricePerTonneCents: eur(7200),
    purchasePricePerTonneCents: eur(6250),
    closeProbability: 1,
    ownerId: "ceo",
    createdAt: daysAgo(20),
    lastContactAt: daysAgo(14),
    documents: ["COA", "ORIGIN", "INVOICE", "PACKING_LIST"],
    riskFlags: [],
    businessLine: "ATELIER",
  },
];

export const documents: TrackedDocument[] = [
  {
    id: "doc-1",
    type: "COMPANY_REGISTRATION",
    companyId: "sup-metalsud",
    issueDate: daysAgo(400),
    verificationStatus: "VERIFIED",
    verifiedAt: daysAgo(30),
    verifiedBy: "ceo",
  },
  {
    id: "doc-2",
    type: "COA",
    dealId: "deal-2",
    companyId: "sup-metalsud",
    issueDate: daysAgo(6),
    verificationStatus: "VERIFIED",
    verifiedAt: daysAgo(5),
    verifiedBy: "ceo",
  },
  {
    id: "doc-3",
    type: "ASSAY",
    dealId: "deal-1",
    companyId: "sup-katanga",
    issueDate: daysAgo(18),
    verificationStatus: "PENDING",
  },
  {
    id: "doc-4",
    type: "ORIGIN",
    dealId: "deal-1",
    companyId: "sup-katanga",
    verificationStatus: "UNVERIFIED",
    notes: "Certificat d'origine à obtenir avant contrat.",
  },
  {
    id: "doc-5",
    type: "LICENSE",
    companyId: "sup-brassco",
    issueDate: daysAgo(200),
    expiryDate: daysFromNow(20),
    verificationStatus: "VERIFIED",
    verifiedAt: daysAgo(60),
    verifiedBy: "ceo",
    notes: "Expire bientôt.",
  },
  {
    id: "doc-6",
    type: "IDENTITY",
    companyId: "buy-quickcash",
    verificationStatus: "REJECTED",
    notes: "Pièce d'identité non concordante.",
  },
  {
    id: "doc-7",
    type: "CONTRACT",
    dealId: "deal-5",
    companyId: "buy-fonderie",
    issueDate: daysAgo(3),
    expiryDate: daysFromNow(2),
    verificationStatus: "PENDING",
    notes: "En attente de signature.",
  },
  {
    id: "doc-8",
    type: "COA",
    companyId: "sup-recyclyon",
    issueDate: daysAgo(90),
    expiryDate: daysAgo(3),
    verificationStatus: "VERIFIED",
    notes: "Expiré, à renouveler.",
  },
];

export const followUps: FollowUp[] = [
  {
    id: "fu-1",
    dealId: "deal-4",
    companyId: "buy-fonderie",
    action: "Confirmer l'enlèvement Millberry à Lyon",
    ownerId: "ceo",
    priority: "WARM",
    dueAt: daysFromNow(0),
    lastContactAt: daysAgo(3),
    done: false,
  },
  {
    id: "fu-2",
    dealId: "deal-2",
    companyId: "buy-cableplus",
    action: "Relancer CâblePlus sur l'offre busbars",
    ownerId: "ceo",
    priority: "HOT",
    dueAt: daysAgo(1),
    lastContactAt: daysAgo(4),
    done: false,
  },
  {
    id: "fu-3",
    dealId: "deal-5",
    companyId: "buy-fonderie",
    action: "Faire signer le contrat laiton",
    ownerId: "ceo",
    priority: "HOT",
    dueAt: daysAgo(2),
    lastContactAt: daysAgo(9),
    done: false,
  },
  {
    id: "fu-4",
    dealId: "deal-1",
    companyId: "sup-katanga",
    action: "Obtenir le certificat d'origine Katanga",
    ownerId: "ceo",
    priority: "HOT",
    dueAt: daysFromNow(1),
    lastContactAt: daysAgo(20),
    done: false,
  },
  {
    id: "fu-5",
    companyId: "buy-comptoir",
    action: "Réactiver Comptoir des Métaux (dormant)",
    ownerId: "ceo",
    priority: "COOL",
    dueAt: daysFromNow(2),
    lastContactAt: daysAgo(120),
    done: false,
  },
  {
    id: "fu-6",
    dealId: "deal-3",
    companyId: "buy-elektro",
    action: "Chiffrer logistique cathode Elektro",
    ownerId: "ceo",
    priority: "WARM",
    dueAt: daysFromNow(2),
    lastContactAt: daysAgo(4),
    done: false,
  },
  {
    id: "fu-7",
    dealId: "deal-7",
    companyId: "buy-alumex",
    action: "Envoyer prix ferme aluminium",
    ownerId: "ceo",
    priority: "WARM",
    dueAt: daysFromNow(3),
    lastContactAt: daysAgo(6),
    done: false,
  },
];

export const quotes: Quote[] = [
  {
    id: "q-1",
    supplierId: "sup-metalsud",
    buyerId: "buy-cableplus",
    material: "COPPER_BARS_BUSBARS",
    grade: "A",
    quantityKg: 10000,
    purchasePricePerTonneCents: eur(9350),
    transportCents: eur(850),
    insuranceCents: eur(120),
    customsFeesCents: eur(0),
    financingCents: eur(300),
    otherCostsCents: eur(80),
    desiredMarginPercent: 9,
    createdAt: daysAgo(5),
  },
  {
    id: "q-2",
    supplierId: "sup-brassco",
    buyerId: "buy-fonderie",
    material: "BRASS",
    grade: "A",
    quantityKg: 2000,
    purchasePricePerTonneCents: eur(5300),
    transportCents: eur(300),
    insuranceCents: eur(40),
    customsFeesCents: eur(0),
    financingCents: eur(60),
    otherCostsCents: eur(20),
    desiredMarginPercent: 8,
    createdAt: daysAgo(6),
  },
];

export const decisions: Decision[] = [
  {
    id: "dec-1",
    title: "Ne pas acheter la cathode GlobalScrap malgré le prix",
    context: "Offre cathode 20 t à prix très bas, acompte 50% demandé, société non identifiable.",
    decision: "Refus. Fournisseur BLOQUÉ.",
    rationale: "Prix trop beau, acompte suspect, aucune vérification possible. Risque de fraude.",
    expectedOutcome: "Éviter une perte de capital sur une transaction frauduleuse.",
    reviewAt: daysFromNow(60),
    status: "CLOSED",
    createdAt: daysAgo(30),
  },
  {
    id: "dec-2",
    title: "Prioriser le corridor RDC via Metal Corridor plutôt que direct Katanga",
    context: "Katanga en direct mais non vérifié et lent; Metal Corridor propose un canal intermédiaire.",
    decision: "Tester un premier lot via Metal Corridor sous vérification.",
    rationale: "Réduire le risque documentaire et logistique sur le premier flux RDC.",
    expectedOutcome: "Premier flux RDC sécurisé, base pour scaler le corridor.",
    reviewAt: daysFromNow(45),
    status: "OPEN",
    createdAt: daysAgo(10),
  },
];
